### ISSUE TITLE
About Statifier's Segmentation Fault

### ISSUE THREAD

**Issue by tbinjiayou** [baidu/ins#22]
利用Statifier静态编译打包可执行程序需要将机器的randomize_va_space置0，禁止地址随机化，否则可能引发段错误。
但是为什么ins的Statifier打包文件却可以在非0的机器上运行？是否有做什么特殊处理？真心求解

**Comment by fxsjy** [comment]
@tbinjiayou ， 我对statifier理解不深。直接拿来用的，没有加任何参数。`statifier ins ins.2` 大概就是这样。 我在Centos4下用statifier处理的，然后在阿里云上用Centos6和Ubuntu的机器都测试了下，都直接能跑，就没研究细节了。没有应对randomize_va_space=1做任何事情。
内存管理方面，我没做啥特殊的处理, 只是链接了tcmalloc。
