### ISSUE TITLE
log

### ISSUE THREAD

**Issue by demiaowu** [baidu/ins#38]
Building error:
/common/logging.h:55:57: error: unable to find string literal operator ‘operator""fmt’ with ‘const char [9]’, ‘long unsigned int’ arguments
 #define LOG(level, fmt, args...) ins_common::Log(level, "[%s:%d] "fmt, __FILE__, __LINE__, ##args)

**Comment by Kai-Zhang** [comment]
LOG这个宏使用的时候fmt是字符串常量，两个字符串字面常量放在一起编译器会自动拼接的
能不能提供一下你的编译器的版本我们这边尝试复现一下

**Comment by demiaowu** [comment]
1. g++ --version:
        g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005
        Copyright (C) 2016 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

2. Personal proposal:
/common/logging.h:55:57:
#define LOG(level, fmt, args...) ins_common::Log(level, fmt, __FILE__, __LINE__, ##args)  

/common/logging.cc:371:379
void Log(int level, const char* fmt, ...) {
    size_t head_len = strlen("[%s:%d] ");
    size_t fmt_len  = strlen(fmt); 
    char* fmtp      = new char[head_len + fmt_len];
               
    memcpy(fmtp, "[%s:%d] ", head_len);
    memcpy(fmtp+head_len, fmt, fmt_len);
	
    va_list ap;
    va_start(ap, fmtp);

    if (level >= g_log_level) {
        Logv(level, fmtp, ap);
    }
    va_end(ap);
}

**Comment by demiaowu** [comment]
2. Personal proposal:
/common/logging.h:55
#define LOG(level, fmt, args...) ins_common::Log(level, fmt, __FILE__, __LINE__, ##args)

/common/logging.cc:371
void Log(int level, const char* fmt, ...) {
	size_t head_len = strlen("[%s:%d] ");
	size_t fmt_len  = strlen(fmt); 
	
	char* fmtp = new char[head_len + fmt_len];

    memcpy(fmtp, "[%s:%d] ", head_len);
    memcpy(fmtp + head_len, fmt, fmt_len);
	
    fmt = fmtp;

    va_list ap;
    va_start(ap, fmt);

    if (level >= g_log_level) {
        Logv(level, fmt, ap);
    }
    va_end(ap);

    delete fmtp;
}

**Comment by bluebore** [comment]
这个问题在baidu/common里是不是早就修复了，ins还在用自己的common么？

**Comment by Kai-Zhang** [comment]
日志这个用动态内存分配的效率太低了，我这边在ubuntu上试了下是可以编译成功的

**Comment by Kai-Zhang** [comment]
这个common就是从baidu/common里拉取的最新的logging

**Comment by demiaowu** [comment]
不知道问题是不是出再这里：我在自己的机器上面单独写了一个测试的例子，当"[%s:%d] "fmt之间没有空格时会报错，报错同上面的一样；如果加一个空格，"[%s:%d] " fmt之后就没问题，现在ins master上面的"[%s:%d] "和fmt之间没有空格，有点诡异（我的g++版本如上所述），麻烦您再确认一下，Thanks~

**Comment by yvxiang** [comment]
如果不加空格的话，可能导致部分版本的编译器有warning，这个问题在common库的cpp11分支里修过

**Comment by demiaowu** [comment]
我这边报的是error。 : )

**Comment by Kai-Zhang** [comment]
ok如果是空格的问题我改一下

**Comment by bluebore** [comment]
把这个common也merge到baidu/common里去吧，否则两边修复的问题没法共享。
